services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9200:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus:
